tall.---
title: "msc-phygeo-eo-ws-01-1"
author: "MOC - Environmental Observations (F. Detsch, C. Reudenbach, T. Nauss)"
date: "30 März 2017"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
source("C:/Users/tnauss/permanent/edu/msc-phygeo-environmental-observation/scripts/msc-phygeo-environmental-observation/src/functions/set_environment.R")
```

## MaxENT species random/background random grid dataset (sr_br)
```{r}
hessen <- readRDS(paste0(path_rdata, "v_hessen.rds"))
sr_br <- readRDS(paste0(path_rdata, "sr_br.rds"))
env <- readRDS(paste0(path_rdata, "s_env.rds"))
mi_env <- env[[1:5]]

s = 1
sf = 1

cur_sr_br <- sr_br[[s]]
cur_sr_br_sf <- cur_sr_br[[sf]]


me <- dismo::maxent(mi_env, p = cur_sr_br_sf$training$occurence, a = cur_sr_br_sf$training$background, 
                    factors = c("g100_clc12_V18_5", "FAD_eur_020m_fin", "FTY_eur_020m_fin"), 
                    path = paste0(path_model, "me_sr_br_s01_f01"))
me

# plot showing importance of each variable
plot(me)
pairs(me, pa = "pa")

# response curves
# par(mar=c(1,1,1,1))
response(me)

# evaluate
e_test <- dismo::evaluate(p=cur_sr_br_sf$test$occurence, a=cur_sr_br_sf$test$background, model = me, x = mi_env)
threshold(e_test)
plot(e_test, 'ROC')
boxplot(e_test)
density(e_test)

# spatial bias
sb <- dismo::ssb(cur_sr_br_sf$test$occurence, cur_sr_br_sf$test$background, cur_sr_br_sf$training$occurence)
sb[1]/sb[2]

p_all <- dismo::predict(me, env) 
saveRDS(p_all, paste0(path_rdata, "me_sr_br_s01_f01_hessen.rds"))

plot(p_all)
points(cur_sr_br_sf$training$occurence, col = "red")
points(cur_sr_br_sf$test$occurence, col = "blue")
points(cur_sr_br_sf$training$background, col = "grey")
points(cur_sr_br_sf$test$background, col = "grey")

map.colors = colorRampPalette(c("#FC8D59", "#FEE08B","#99D594", "#3288BD"))
spplot(p_all, col.regions =map.colors(1000),
       colorkey = list(space="right"), cuts = c(100), at = seq(0, 1, by = 0.01),
       scales = list(draw = TRUE),
       key=list(corner=c(0,0.02),cex=0.9, #space = 'bottom', 
                points = list(pch = 15, cex = 1, col = c("blue","darkblue","darkgreen")),
                text = list(c("Presence training",
                              "Presence test",
                              "Absence")))) +
  as.layer(spplot(cur_sr_br_sf$training$occurence, zcol = "NAME", col.regions="blue", colorkey=FALSE)) +
  as.layer(spplot(cur_sr_br_sf$test$occurence, zcol = "NAME", col.regions="darkblue", colorkey=FALSE)) +
  as.layer(spplot(hessen, zcol = "ID_0", colorkey=FALSE))

```




## MaxENT
```{r}
soc_all_env_df <- readRDS(paste0(path_rdata, "soc_all_env_df.rds"))

i = 1
meta <- c("NAME", "TYPE", "LAT", "LON")

sae_df <- soc_all_env_df[[i]]
sae_df <- sae_df[, -c(which(colnames(sae_df) %in% "wc2.0_30s_prec_01"):which(colnames(sae_df) %in% "wc2.0_30s_wind_12"))]

str(sae_df)
predictors <- sae_df[, which(!colnames(sae_df) %in% meta)]
type <- sae_df$TYPE


# str(predictors)
# cor_pred <- cor(predictors[, c(-1, -3, -4, -5)])


fold <- dismo::kfold(sae_df$TYPE, k=5)


train <- predictors[fold != 1, ]
train_type <- type[fold != 1]

test <- predictors[fold == 1, ]
test_type <- type[fold == 1]

# fit model, biome is a categorical variable
me <- maxent(train, p = train_type, path = paste0(path_model, "test"))

# see the maxent results in a browser:
me

# plot showing importance of each variable
plot(me)

# response curves
# par(mar=c(1,1,1,1))
response(me)

# predict to entire dataset
p_test <- dismo::predict(me, test) 
p_test_occ <- p_test[test_type == 1]
p_test_bg <- p_test[test_type == 0]


#simplest way to use 'evaluate'
e_test <- dismo::evaluate(p=p_test_occ, a=p_test_bg, model = me)
threshold(e_test)
plot(e_test, 'ROC')

# use "args"
# me2 <- maxent(predictors, occtrain, factors='biome', args=c("-J", "-P"))

# with some options:
# r <- predict(me, predictors, args=c("outputformat=raw"), progress='text', 
#      filename='maxent_prediction.grd')

plot(r)
points(occ)


env <- readRDS(paste0(path_rdata, "s_env.rds"))

p_all <- dismo::predict(me, env) 
plot(p_all)
saveRDS(me, file = paste0(path_rdata, "sae_maxent_somatochlora_arctica.rds"))
saveRDS(p_all, file = paste0(path_rdata, "sae_maxent_somatochlora_arctica_prediction.rds"))
```