# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# moer: Adjust title etc. Depending on serving the site on GitHub or OER, different
# url/baseurl settings have to be used.


title: Environmental Observations | Lab of Environmental Informatics
name: &name "Thomas Nauss" # &name is a YAML anchor which can be *referenced later
email: nauss@geo.uni-marburg.de
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
title_separator: "|"

#url: "https://oer.uni-marburg.de"
#baseurl: "/data/mriliasmooc/lm_data/lm_2422"
url: https://marburg-open-courseware.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/moer-envobs" # the subpath of your site, e.g. "/blog"

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# moer: Adjust theme etc.
markdown: kramdown
# theme: minima
remote_theme: "marburg-open-courseware/jekyll-template-moer"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
auto_ids: true

# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/tnauss.jpg"
  bio              : "Marburg University"
  location         : "Marburg, DE"
  email            : "nauss@geo.uni-marburg.de"
  uri              : "https://www.uni-marburg.de/fb19/fachgebiete/umweltinformatik/"
  home             : "https://www.uni-marburg.de/fb19/fachgebiete/umweltinformatik/nausst/index.html"
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           : "https://www.flickr.com/environmentalinformatics-marburg/"
  facebook         : "https://www.facebook.com/GeographieMarburg/"
  foursquare       :
  github           : "github.com/marburg-open-courseware"
  gitlab           :
  google_plus      :
  keybase          :
  instagram        : 
  lastfm           :
  linkedin         :
  pinterest        :
  soundcloud       :
  stackoverflow    : # https://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : "https://twitter.com/geographie_umr"
  vine             :
  weibo            :
  xing             :
  youtube          : "https://www.youtube.com/channel/UCGiwSv5KYjsNXl6-nZq0SDA"




# moer: Add collections and default styles.
include:
  - _pages
  
collections:
  examples:
    output: true
    permalink: /:collection/:title.html
  lectures:
    output: true
    permalink: /:collection/:title.html
  units:
    output: true
    permalink: /:collection/:title.html
  unit01:
    output: true
    permalink: /:collection/:title.html
  unit02:
    output: true
    permalink: /:collection/:title.html
  worksheets:
    output: true
    permalink: /:collection/:title.html

defaults:
  # examples
  - scope:
      path: ""
      type: examples
    values:
      category: "examples"
      layout: single
      sidebar:
        nav: "docs" 
  # lectures
  - scope:
      path: ""
      type: lectures
    values:
      category: "lectures"
      layout: single
      sidebar:
        nav: "docs"
  # units
  - scope:
      path: ""
      type: units
    values:
      category: "units"
      layout: single
      sidebar:
        nav: "docs" 
  # unit01
  - scope:
      path: ""
      type: unit01
    values:
      category: "unit01"
      layout: single
      sidebar:
        nav: "docs" 
  # unit02
  - scope:
      path: ""
      type: unit02
    values:
      category: "unit02"
      layout: single
      sidebar:
        nav: "docs" 
  # worksheets
  - scope:
      path: ""
      type: worksheets
    values:
      category: "worksheets"
      layout: single
      sidebar:
        nav: "docs"        
  # pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"        

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-cayman
