# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# moer: Adjust title etc. Depending on serving the site on GitHub or OER, different
# url/baseurl settings have to be used.
title: Environmental Informatics
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "/data/mriliasmooc/lm_data/lm_2291"
# url: "https://oer.uni-marburg.de"
baseurl: "msc-phygeo-environmental-observations-moer"
url: "http://marburg-open-courseware.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
# moer: Adjust theme etc.
markdown: kramdown
# theme: minima
remote_theme: "mmistakes/minimal-mistakes"

# moer: Add collections and default styles.
include:
  - _pages
  
collections:
  examples:
    output: true
    permalink: /:collection/:path
  lectures:
    output: true
    permalink: /:collection/:path
  worksheets:
    output: true
    permalink: /:collection/:path

defaults:
  # examples
  - scope:
      path: ""
      type: examples
    values:
      category: "examples"
      layout: single
      sidebar:
        nav: "docs" 
  # lectures
  - scope:
      path: ""
      type: lectures
    values:
      category: "lectures"
      layout: single
      sidebar:
        nav: "docs"
  # worksheets
  - scope:
      path: ""
      type: worksheets
    values:
      category: "worksheets"
      layout: single
      sidebar:
        nav: "docs"        
  # pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"        

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
